### ISSUE TITLE
Cache autogenerated Search key values for dropdowns in database

### ISSUE THREAD

**Issue by lukehollis** [cltk/cltk_frontend#99]
Right now it takes too long for the autogenerated search tool parameters to appear when the page loads. These values are generated here https://github.com/cltk/cltk_frontend/blob/develop/server/methods/searchTools.js need to be cached in the database somewhere so that they're not recreated on each user session.

**Comment by pletcher** [comment]
Hi @lukehollis, is this issue free? I had a spare moment and resolved it locally with a collection in Mongo:

```javascript
import Authors from '/imports/collections/authors';
import Works from '/imports/collections/works';

SearchToolsCache = new Mongo.Collection('searchTools_cache');

SearchToolsCache._ensureIndex({ key: 1 });
SearchToolsCache._ensureIndex({ createdAt: 1 }, { expireAfterSeconds: 3600 });

function get() {
	const result = SearchToolsCache.findOne({ 
		key: 'searchTools_cache' 
	}, { 
		_id: false, 
		value: true 
	}) || {};

	return result.value;
}

function set(value) {
	SearchToolsCache.insert({
		key: 'searchTools_cache',
		value,
		createdAt: new Date()
	});
}

Meteor.methods({
	searchTools() {
		const cachedResult = get();

		if (cachedResult) {
			return cachedResult;
		}

                // etc...

		const result = {
			languages,
			corpora,
			authors,
		};

		set(result);

		return result;
	},

});
```

This is clearly a little messy, but I wanted to pause to get feedback since this'd be my first contribution to the project. 

A couple of questions:

1. Is it okay to use MongoDB for caching like this, or should I set up something like Redis in the PR?
2. Does the CLTK want a general-purpose cache (i.e., one that, unlike the above example, isn't tied specifically to `searchTool()`)? If so, where should that live?

It also seems to me that it might be preferable to cache something like arrays of IDs for each of the collections involved in `searchTool()` -- that way we could avoid the enormous documents that are cached in the above example. Would be more than happy to implement the cache that way.

Please feel free to let me know if I've totally gone off into the woods with respect to what you were expecting! Thanks!

**Comment by lukehollis** [comment]
@pletcher, this solution looks optimal for the search tools right now. I was having trouble getting the languages to work locally, and I realized that we had to augment the schema slightly in recent iterations of the project because Mongo was using the 'language' field for text indexes (https://docs.mongodb.com/manual/tutorial/specify-language-for-text-index/). The new database is now in the README and available here: https://storage.googleapis.com/archimedes-data--regional/cltk/dump-without-users.tgz 

Specifically to your question, we might need other sorts of caching in the future, but I'm afraid of over-optimizing before we need to. I think this is the perfect level of caching for the application search tools and can be extended in the future when we hit other bottlenecks. Caching the IDs is a great idea and seems to be working well. 

Otherwise, I've merged back to master with this integrated and will build and release. Awesome work, and thanks again.

**Comment by pletcher** [comment]
@lukehollis Thanks, I'll update my local copy of the database.

And I'm with you on avoiding over-optimizing at the moment. Thanks for reviewing my PRs so quickly!

I also wanted to ask (although maybe extending this thread is the wrong way to go about it -- happy to open another issue if you'd prefer): I needed to update a few packages to get things working locally (specifically, I bumped `material-ui` to `0.16.4` (because of its dependency on `react-tap-event-plugin`, if I remember right), `react` and `react-dom` to `15.4.1`, and `react-tap-event-plugin` to `2.0.1`. I also needed to bump Meteor itself to `1.4.3.2` for the project to build. I didn't commit these changes, since they seemed to be outside the scope of this issue, but I wanted to mention them before I forgot.

Thanks again, and please feel free to let me know if there are other issues that I could take a look at! (Or if there's something, like the `languages` issue, that I should fix in any of the changes that I made.)

**Comment by lukehollis** [comment]
Thanks for mentioning that, @pletcher, I believe those were on older versions for compatibility with packages bridging some Blaze resources to React that we might be able to remove now. If everything's working for you after bumping those packages, seems like it'd be really useful to include those changes as well. As far as the other issues, all are still open and relevant--I'm waiting a little right now as @ashiful-haque finalizes the templates, but it appears that they are getting close to being finalized, and if you have any feedback/ideas for them please feel free to voice it on Gitter #ux channel or in an issue on this repo. Thanks for your patience with my following up to your email--will do that now.
